FROM node:latest
# RUN apt-get update
RUN npm install -g  --ignore-scripts @loopback/cli nodemon create-react-app @angular/cli loopback-cli
# Create app directory (with user `node`)
RUN mkdir /app
WORKDIR /app

